services:
  db:
    image: postgres:14
    restart: always
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: qwer4321
      POSTGRES_DB: app_development
    volumes:
      - postgres-data:/var/lib/postgresql/data
      - ./docker/db:/docker-entrypoint-initdb.d


  app:
    build:
      context: .
      dockerfile: ./docker/app/Dockerfile
    command: |
      bash -c
      "yarn install --check-files && \
       bundle install && \
       rake db:migrate && \
       rm -f tmp/pids/server.pid && \
       ./bin/dev"
    stdin_open: true
    tty: true
    volumes:
      - .:/usr/src/app
      - ~/.ssh:/root/.ssh:ro
      - bundle-volume:/usr/local/bundle
    ports:
      - 3000:3000
      - 1234:1234
    environment:
      - REDIS_URL=redis://redis:6379/0
      - DATABASE_URL=postgresql://postgres:qwer4321@db:5432/app_development
    depends_on:
      - db
      - redis

  sidekiq:
    build:
      context: .
      dockerfile: ./docker/app/Dockerfile
    volumes:
      - .:/usr/src/app
      - bundle-volume:/usr/local/bundle
    depends_on:
      - db
      - redis
    environment:
      - REDIS_URL=redis://redis:6379/0
    command: bundle exec sidekiq -C config/sidekiq.yml

  # Redis
  redis:
    image: redis
    command: ["redis-server", "--appendonly", "yes"]
    ports:
      - 6379:6379
    volumes:
      - redis:/data

#Volumes
volumes:
  bundle-volume:
  postgres-data:
  redis:
